name 'ama'
maintainer 'Eric McCullough'
maintainer_email 'eric_mccullough@hotmail.com'
license 'all_rights'
description 'Installs/Configures Automated Malware Analysis server'
long_description 'Installs/Configures an Automated Malware Analysis server'
version '0.1.0'

supports 'ubuntu'

depends 'java'
depends 'elasticsearch'
#depends 'yara'
#depends 'cuckoo'
# depends 'viper'